### ISSUE TITLE
Any updates on the health of the project? :)

### ISSUE THREAD

**Issue by lfilho** [busterjs/buster#453]
Hello guys at @busterjs / @buster. Thanks for this awesome project!!

Is there any word on how buster.js is going? Is it still maintained (i wouldn't say so based merely on the last commits and some PR dates...)?

Since it never reached 1.0 yet, should we move away from it and favor a different toolset?

Thanks a lot.

**Comment by mroderick** [comment]
I am still using BusterJS at any chance I get.
There are still active people in the irc channel.

Perhaps they could just cut a 1.0 release of the current version, which seems quite stable.

**Comment by dominykas** [comment]
I really prefer buster over everything that's available, but honestly I started playing with mocha in quite some of the new things I'm building simply because of the lack of activity here. And I also feel that unless there's an actual company that relies on buster heavily steps up, I highly doubt that this will ever reach 1.0 or get any other serious development at all. </sadpanda>

**Comment by dwittner** [comment]
@lfilho, at the beginning of this year i planned to invest a bit more time in Buster.JS for approximately two month to fix the most important issues and then release version 1.0. Unfortunately, a few days later my boss told me, that i will be very busy the next months, because he wanted me in the development team of a new project. And that's how it is now. Currently i don't have time for Buster.JS. But we use Buster.JS for a few projects in the company i work for and i get paid for working on Buster.JS and at least one project want's me to implement some new features. So the chances are high that i will have more time for Buster.JS in a few days/weeks. And i hope, that with version 1.0 of Buster.JS more developers will contribute for the project and thus the progress will accelerate.
