### ISSUE TITLE
Replace tmpvar/jsdom with cheeriojs/cheerio?

### ISSUE THREAD

**Issue by mroderick** [busterjs/buster#456]
Recently, [`contextify` has started failing to build on `node@0.6` on both Linux and OSX](https://github.com/cjohansen/Sinon.JS/pull/783).

The only dependency on contextify that I can find Buster modules, is in `tmpvar/jsdom`, which only supports `iojs` since v4.0, so we won't be able to upgrade ourselves out of this problem or any future problems with `jsdom`. Even if/when node and iojs merges, it's clear that `jsdom` project is not interested in maintaining compatibility with legacy node versions (which is a valid choice).

With that in mind, I think it is too much effort to get `contextify` building on `node@0.6`, only to be stuck with a `jsdom` dependency that we can no longer upgrade. I've looked around, and while there are forks of `jsdom` for `node`, none seem to be that well maintained.

Also: `jsdom` doesn't seem to work well in `node@0.12`, as you can see in [my PR to run tests in more node versions](https://github.com/busterjs/buster-test/pull/30)

Would you consider merging a pull request that replaces the use of `tmpvar/jsdom` with `cheeriojs/cheerio`?

Also, why are there two html reporters? (I'd like to avoid duplication of effort, if I can)

**Comment by dwittner** [comment]
@mroderick, if `cheeriojs/cheerio` fits all our needs, there is nothing against it. Does `cheeriojs/cheerio` needs `node-gyp` for installation? If not, this would be an advantage too.

**Comment by dominykas** [comment]
`cheerio` won't help in `buster-test` - the way `jsdom` is used, is to construct a full browser-like environment, and then regular DOM functions are being used to build the reporter output. `cheerio` only provides a jquery-like API to deal with HTML. It might just be enough to build the output, but it would also mean that a compatible module would be needed on the browser side and I'd really hate to add jquery itself as a dependency.

Investigating alternatives...

**Comment by dominykas** [comment]
Some alternatives I'm thinking about: 

* Remove `jsdom` from `optionalDependencies` and be done with it. There's no way to ensure inside `package.json` the correct version for all nodes - only <=v3 works in 0.10/0.12, only >=v4 works in 4/5. Since it's only being used in `html`/`html2` reporters on node side, it should be safe to not even bother installing it - the end users can install it themselves if they really really want to use these reporters in node side, and not in the browser. I can configure Travis easily to run tests with a correct version.
* Install `jsdom@latest` and also `jsdom-compat` side by side, pick the correct one based on environment (I'm kind of reluctant to do this, as buster's installation is already taking ages... but this would solve the problem of ensuring there's at least one valid `jsdom` installed)
* Use React's `virtual-dom` / `vdom-virtualize` (not sure about the effort involved...)

**Comment by mroderick** [comment]
I think we should just get rid of it. That will benefit most users

**Comment by dominykas** [comment]
Wait, actually, 3.x series seem to work in all nodes, so that could be a stopgap solution, although I'm in favour of just removing it to speed up install - not sure it really brings value being there.

**Comment by dominykas** [comment]
A little bit late to the party, contextify actually release a 0.1.15 some 10 days ago - which luckily allowed me to upgrade `jsdom` to v3 in `buster-test`, which I will release as soon as all Travis builds pass (something odd with npm install is breaking them occasionally...) - so that solves the immediate problem. As for the future - we'll see :)
